// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/account': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/account/index').default>>>>
    }
    '/api/attribute': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/attribute/index').default>>>>
    }
    '/api/blog': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/index').default>>>>
    }
    '/api/blog/slug/:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/slug/[slug]').default>>>>
    }
    '/api/cart': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/index').default>>>>
    }
    '/api/category/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/category/[id]').default>>>>
    }
    '/api/category': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/category/index').default>>>>
    }
    '/api/compare/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/compare/[id]').default>>>>
    }
    '/api/compare': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/compare/index').default>>>>
    }
    '/api/contact-us': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact-us/index').default>>>>
    }
    '/api/country': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/country/index').default>>>>
    }
    '/api/coupon': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/coupon/index').default>>>>
    }
    '/api/currency': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/currency/index').default>>>>
    }
    '/api/faq': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/faq/index').default>>>>
    }
    '/api/front/review': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/front/review/index').default>>>>
    }
    '/api/home': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/index').default>>>>
    }
    '/api/notification': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notification/index').default>>>>
    }
    '/api/order/:order_number': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/order/[order_number]').default>>>>
    }
    '/api/order': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/order/index').default>>>>
    }
    '/api/orderStatus': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orderStatus/index').default>>>>
    }
    '/api/page': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page/index').default>>>>
    }
    '/api/payment-account': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment-account/index').default>>>>
    }
    '/api/points/consumer': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/points/consumer/index').default>>>>
    }
    '/api/product': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/product/index').default>>>>
    }
    '/api/product/slug/:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/product/slug/[slug]').default>>>>
    }
    '/api/question-and-answer': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/question-and-answer/index').default>>>>
    }
    '/api/refund': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refund/index').default>>>>
    }
    '/api/review': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/review/index').default>>>>
    }
    '/api/self': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/self/index').default>>>>
    }
    '/api/settings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index').default>>>>
    }
    '/api/state': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/state/index').default>>>>
    }
    '/api/store': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/index').default>>>>
    }
    '/api/store/slug/:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/slug/[slug]').default>>>>
    }
    '/api/tag': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tag/index').default>>>>
    }
    '/api/theme/berlin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/berlin/index').default>>>>
    }
    '/api/theme/denver': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/denver/index').default>>>>
    }
    '/api/theme/madrid': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/madrid/index').default>>>>
    }
    '/api/theme/osaka': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/osaka/index').default>>>>
    }
    '/api/theme/paris': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/paris/index').default>>>>
    }
    '/api/theme/rome': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/rome/index').default>>>>
    }
    '/api/theme/tokyo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/theme/tokyo/index').default>>>>
    }
    '/api/themeOptions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/themeOptions/index').default>>>>
    }
    '/api/wallet/consumer': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet/consumer/index').default>>>>
    }
    '/api/wishlist': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}